config/routes.rb
PdfkitPdf::Application.routes.draw do
   root :to => 'users#index'
    get "users/welcome"
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def welcome
    
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PdfkitPdf</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
<body>


<div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
        
       <%= render 'header' %>
     </div>
   </div>
 </div>



<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New User', new_user_path %>
<p><%= link_to 'Pdf Doc', users_path(:format => "pdf")   %></p>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<h1>welcome</h1>
<p>
    Dear <b><i><u><%= @user.name %></u></i></b>
    <p>
    </p>
</p>
<p>
</p>
<p>
    Welcome to RupeeVest! We are honored to be the financial services provider for your family’s investment needs.
    <p>
    </p>
</p>
<p>
</p>
<p>
    Managing your personal investments will never be the same again. Using RupeeVest’s unique state-of-the- art platform you will be able to plan, invest and
    track with the confidence of a professional at the comfort of your home. You will be able to make use of the value-added services we provide to have an
    informed access and empowered control of your investments.
    <p>
    </p>
</p>
<p>
</p>
<p>
    Your User id is: <b><i><u> <%= @user.email %></u></i></b>
    <u>
        <p>
        </p>
    </u>
</p>
<p>
</p>
<p>
    To complete your account opening process and start your investments with us, we need you to send us the application form and a few required documents. You
    will find the full list of documents that we need in the enclosed “Document Checklist”.
    <p>
    </p>
</p>
<p>
</p>
<p>
    <b>Please read and ensure that you mail us the entire list of documents from the “Document Checklist” to avoid any delay in processing your application</b>
    .
    <p>
    </p>
</p>
<p>
</p>
<p>
    Please also find attached the terms and conditions of using our services. Please go through it carefully, and maintain it for your records.
    <p>
    </p>
</p>
<p>
</p>
<p>
    <b>If you have chosen to send the forms to us yourself:</b>
    <p>
    </p>
</p>
<p>
</p>
<p>
    Please send all the documents, including the signed application form and terms &amp; condition document to:
    <p>
    </p>
</p>
<p>
</p>
<p>
    RV Financial Services Private Limited
    <p>
    </p>
</p>
<p>
</p>
<p>
    5B Judges Court Road, Flat No – 6B
    <p>
    </p>
</p>
<p>
    Kolkata, West Bengal 700027. Telephone Number: 91-7406998067
    <p>
    </p>
</p>
<p>
</p>
<p>
</p>
<p>
</p>
<p>
    If you have any question regarding either the application form or the documents required please get in touch with us at <u>info@RupeeVest.com</u> or call
    us at 91-7406998067.
    <p>
    </p>
</p>
<p>
</p>
<p>
    Once again thank you for choosing RupeeVest.com
    <p>
    </p>
</p>
<p>
</p>
<p>
    Warm Regards
    <p>
    </p>
</p>
<p>
</p>
<p>
    Happy RupeeVesting!
    <p>
    </p>
</p>

<p id="pdf_link"><%= link_to " Download (PDF)", user_path(@user, :format => "pdf" ) %></p>

app/views/users/welcome.html.erb
<p id="notice"><%= notice %></p>

<link rel="stylesheet" href="stylesheets/style.css">
<h1>welcome</h1>
<p>
    Dear <b><i><u></u></i></b>
    <p>
    </p>
</p>
<p>
</p>
<p>
    Welcome to RupeeVest! We are honored to be the financial services provider for your family’s investment needs.
    <p>
    </p>
</p>
<p>
</p>
<p>
    Managing your personal investments will never be the same again. Using RupeeVest’s unique state-of-the- art platform you will be able to plan, invest and
    track with the confidence of a professional at the comfort of your home. You will be able to make use of the value-added services we provide to have an
    informed access and empowered control of your investments.
    <p>
    </p>
</p>
<p>
</p>
<p>
    Your User id is: <b><i><u></u></i></b>
    <u>
        <p>
        </p>
    </u>
</p>
<p>
</p>
<p>
    To complete your account opening process and start your investments with us, we need you to send us the application form and a few required documents. You
    will find the full list of documents that we need in the enclosed “Document Checklist”.
    <p>
    </p>
</p>
<p>
</p>
<p>
    <b>Please read and ensure that you mail us the entire list of documents from the “Document Checklist” to avoid any delay in processing your application</b>
    .
    <p>
    </p>
</p>
<p>
</p>
<p>
    Please also find attached the terms and conditions of using our services. Please go through it carefully, and maintain it for your records.
    <p>
    </p>
</p>
<p>
</p>
<p>
    <b>If you have chosen to send the forms to us yourself:</b>
    <p>
    </p>
</p>
<p>
</p>
<p>
    Please send all the documents, including the signed application form and terms &amp; condition document to:
    <p>
    </p>
</p>
<p>
</p>
<p>
    RV Financial Services Private Limited
    <p>
    </p>
</p>
<p>
</p>
<p>
    5B Judges Court Road, Flat No – 6B
    <p>
    </p>
</p>
<p>
    Kolkata, West Bengal 700027. Telephone Number: 91-7406998067
    <p>
    </p>
</p>
<p>
</p>
<p>
</p>
<p>
</p>
<p>
    If you have any question regarding either the application form or the documents required please get in touch with us at <u>info@RupeeVest.com</u> or call
    us at 91-7406998067.
    <p>
    </p>
</p>
<p>
</p>
<p>
    Once again thank you for choosing RupeeVest.com
    <p>
    </p>
</p>
<p>
</p>
<p>
    Warm Regards
    <p>
    </p>
</p>
<p>
</p>
<p>
    Happy RupeeVesting!
    <p>
    </p>
</p>

<p id="pdf_link"><%= link_to " Download (PDF)", users_welcome_path(@user, :format => "pdf" ) %></p>